version: "3"
services:
  dev-image:
    image: ${IMAGE_TAG}:${IMAGE_VERSION}
    stdin_open: true
    tty: true
    ports:
      - "8081:8081"
    container_name: debug_env
    privileged: true
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
     - ../../:/${WORK_DIR}
     - /dev:/dev 
    command: '/bin/bash' 
