@echo off

:: Setting the Docker Image parameters

echo Setting the Docker Image parameters

call %~dp0gcc-arm-none-eabi-7-2018-q2-update-linux\env.cmd
call %~dp0dashboard\env.cmd

set IMAGE_TAG=%DOCKER_IMAGE_TAG%
set IMAGE_VERSION=%DOCKER_IMAGE_VERSION%

echo Setting the Docker Image parameters Dashboard parameters



set IMAGE_TAG_GRAFANA=%GRAFANA_DOCKER_IMAGE_TAG%
set IMAGE_VERSION_GRAFANA=%GRAFANA_DOCKER_IMAGE_VERSION%


set IMAGE_TAG_ECLIPSE_MOSQUITTO=%ECLIPSE_MOSQUITTO_DOCKER_IMAGE_TAG%
set IMAGE_VERSION_ECLIPSE_MOSQUITTO=%ECLIPSE_MOSQUITTO_DOCKER_IMAGE_VERSION%

set IMAGE_TAG_INFLUXDB=%INFLUXDB_DOCKER_IMAGE_TAG%
set IMAGE_VERSION_INFLUXDB=%INFLUXDB_DOCKER_IMAGE_VERSION%

set IMAGE_TAG_TELEGRAF=%TELEGRAF_DOCKER_IMAGE_TAG%
set IMAGE_VERSION_TELEGRAF=%TELEGRAF_DOCKER_IMAGE_VERSION%


set WORK_DIR=/workspace
