/* Region size (in bytes) */
__REGION_SIZE__ = 0x2800;

/* Cloud settings json mcu internal flash address*/
__MCU_CLOUD_SETTINGS_REGION_START_ADDRESS__ = 0x8EFA000;

/*  Device Certificate MCU internal flash address */
__MCU_DEVICE_CERTIFICATE_REGION_START_ADDRESS__ = 0x8EFB000;

/*  Private Key MCU internal flash address */
__MCU_PRIVATE_KEY_REGION_START_ADDRESS__  = 0x8EFC000;

/*  Root Cert MCU internal flash address */
__MCU_ROOT_CERT_REGION_START_ADDRESS__ = 0x8EFD000; 
