
#!/bin/bash

ECLIPSE_MOSQUITTO_DOCKER_IMAGE_TAG="eclipse-mosquitto"
ECLIPSE_MOSQUITTO_DOCKER_IMAGE_VERSION="latest"

INFLUXDB_DOCKER_IMAGE_TAG="influxdb"
INFLUXDB_DOCKER_IMAGE_VERSION="1.8"

TELEGRAF_DOCKER_IMAGE_TAG="telegraf"
TELEGRAF_DOCKER_IMAGE_VERSION="latest"

GRAFANA_DOCKER_IMAGE_TAG="grafana/grafana"
GRAFANA_DOCKER_IMAGE_VERSION="latest"