#!/bin/bash

. gcc-arm-none-eabi-7-2018-q2-update-linux/env.sh
. dashboard/env.sh


export IMAGE_TAG=${DOCKER_IMAGE_TAG} 
export IMAGE_VERSION=${DOCKER_IMAGE_VERSION}

export WORK_DIR="workspace" 

export IMAGE_TAG_GRAFANA = ${GRAFANA_DOCKER_IMAGE_TAG}
export IMAGE_VERSION_GRAFANA = ${GRAFANA_DOCKER_IMAGE_VERSION}


export IMAGE_TAG_ECLIPSE_MOSQUITTO = ${ECLIPSE_MOSQUITTO_DOCKER_IMAGE_TAG}
export IMAGE_VERSION_ECLIPSE_MOSQUITTO =${ECLIPSE_MOSQUITTO_DOCKER_IMAGE_VERSION}

export IMAGE_TAG_INFLUXDB  = ${INFLUXDB_DOCKER_IMAGE_TAG}
export IMAGE_VERSION_INFLUXDB =${INFLUXDB_DOCKER_IMAGE_VERSION}

export IMAGE_TAG_TELEGRAF =  ${TELEGRAF_DOCKER_IMAGE_TAG}
export IMAGE_VERSION_TELEGRAF = ${TELEGRAF_DOCKER_IMAGE_VERSION}